---
- name: Remove Grafana
  hosts: main
  become: yes
  
  tasks:
  - name: Delete Apt Key
    ansible.builtin.apt_key:
      id: 0E22EB88E39E12277A7760AE9E439B102CF3C0C6
      state: absent

  - name: Remove grafana.list
    ansible.builtin.apt_repository:
      repo: deb https://packages.grafana.com/oss/deb stable main
      filename: grafana
      state: absent

  - name: Ensure Grafana is stopped and disabled
    ansible.builtin.systemd:
      name: grafana-server
      enabled: no
      state: stopped

  - name: Remove Grafana
    ansible.builtin.apt:
      name: grafana
      state: absent

  - name: Remove dependencies that are no longer required
    ansible.builtin.apt:
      autoremove: yes

  - name: Run the equivalent of "apt-get clean" as a separate step
    apt:
      clean: yes
